# Generated by Django 3.0.2 on 2020-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.CharField(choices=[('1', 'Asia'), ('2', 'Europe'), ('3', 'Africa'), ('4', 'Oceania'), ('5', 'America'), ('6', 'Antartica')], max_length=1, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
